apiVersion: v1
kind: Service
metadata:
  name: {{ include "sith-hub.fullname" . }}
  labels:
    {{- include "sith-hub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "sith-hub.selectorLabels" . | nindent 4 }}
